---
- name: Remove metabase HelmChart manifest
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests/metabase-helmchart.yml
    state: absent

- name: Remove metabase secret manifest
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests/metabase-secret.yml
    state: absent

- name: Delete metabase HelmChart CRD to trigger Helm uninstall
  ansible.builtin.command:
    cmd: kubectl -n kube-system delete helmchart metabase --ignore-not-found
  changed_when: false

- name: Wait for K3s to uninstall metabase Helm release
  ansible.builtin.command:
    cmd: kubectl -n {{ metabase_namespace }} get deployment metabase
  register: metabase_check
  changed_when: false
  failed_when: false
  retries: 20
  delay: 15
  until: metabase_check.rc != 0

- name: Delete metabase secret from cluster
  ansible.builtin.command:
    cmd: kubectl -n {{ metabase_namespace }} delete secret metabase-credentials --ignore-not-found
  changed_when: false
