---
- name: Read metabase DB password from SOPS
  ansible.builtin.command:
    cmd: sops -d --extract '["cnpg_metabase_password"]' {{ playbook_dir }}/../inventory/group_vars/all.sops.yml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: metabase_db_password_result

- name: Set metabase DB password fact
  ansible.builtin.set_fact:
    metabase_db_password: "{{ metabase_db_password_result.stdout }}"
  no_log: true

- name: Read metabase encryption secret key from SOPS
  ansible.builtin.command:
    cmd: sops -d --extract '["metabase_encryption_secret_key"]' {{ playbook_dir }}/../inventory/group_vars/all.sops.yml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: metabase_encryption_key_result

- name: Set metabase encryption secret key fact
  ansible.builtin.set_fact:
    metabase_encryption_secret_key: "{{ metabase_encryption_key_result.stdout }}"
  no_log: true
