---
- name: Remove flux
  ansible.builtin.include_tasks: remove.yml
  when: flux_state == 'absent'

- name: Read flux secrets
  ansible.builtin.include_tasks: secret.yml
  when: flux_state == 'present'

- name: Deploy flux namespace
  ansible.builtin.include_tasks: namespace.yml
  when: flux_state == 'present'

- name: Deploy flux
  ansible.builtin.include_tasks: deploy.yml
  when: flux_state == 'present'

- name: Wait for Helm install job to complete
  ansible.builtin.command:
    cmd: kubectl -n kube-system wait --for=condition=complete job/helm-install-flux --timeout=300s
  changed_when: false
  retries: 3
  delay: 15
  register: flux_helm_job
  until: flux_helm_job.rc == 0
  when: flux_state == 'present'

- name: Verify flux
  ansible.builtin.include_tasks: verify.yml
  when: flux_state == 'present'

- name: Bootstrap flux resources
  ansible.builtin.include_tasks: bootstrap.yml
  when: flux_state == 'present'
