---
- name: Read SOPS age private key
  ansible.builtin.slurp:
    src: "{{ flux_sops_age_key_file }}"
  delegate_to: localhost
  become: false
  register: flux_age_key_raw
  no_log: true

- name: Set flux secret facts
  ansible.builtin.set_fact:
    flux_sops_age_key: "{{ flux_age_key_raw.content | b64decode }}"
  no_log: true

- name: Decrypt flux git auth secrets from SOPS
  ansible.builtin.command:
    cmd: sops -d {{ playbook_dir }}/../inventory/group_vars/all.sops.yml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: flux_sops_raw

- name: Set flux git auth facts
  ansible.builtin.set_fact:
    flux_git_username: "{{ (flux_sops_raw.stdout | from_yaml).flux_git_username }}"
    flux_git_password: "{{ (flux_sops_raw.stdout | from_yaml).flux_git_password }}"
    flux_webhook_token: "{{ (flux_sops_raw.stdout | from_yaml).flux_webhook_token }}"
    flux_docker_registry_password: "{{ (flux_sops_raw.stdout | from_yaml).docker_registry_password }}"
  no_log: true
