---
- name: Verify flux source-controller is ready
  ansible.builtin.command:
    cmd: kubectl -n {{ flux_namespace }} rollout status deployment/source-controller --timeout=120s
  changed_when: false

- name: Verify flux kustomize-controller is ready
  ansible.builtin.command:
    cmd: kubectl -n {{ flux_namespace }} rollout status deployment/kustomize-controller --timeout=120s
  changed_when: false

- name: Verify flux helm-controller is ready
  ansible.builtin.command:
    cmd: kubectl -n {{ flux_namespace }} rollout status deployment/helm-controller --timeout=120s
  changed_when: false
