---
galaxy_info:
  role_name: hcloud_csi
  description: Deploy Hetzner Cloud CSI driver on K3s
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
