---
galaxy_info:
  role_name: monitoring
  description: Deploy or remove monitoring stack on K3s
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
