---
galaxy_info:
  role_name: ubuntu24
  description: Base configuration and hardening for Ubuntu 24.04
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
