---

- name: Deploy CNPG cluster manifest
  ansible.builtin.template:
    src: cnpg-cluster.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/cnpg-cluster.yml
    mode: "0600"
- name: Deploy CNPG additional database manifests
  ansible.builtin.template:
    src: cnpg-database.yml.j2
    dest: "/var/lib/rancher/k3s/server/manifests/cnpg-database-{{ item.name | replace('_', '-') }}.yml"
    mode: "0600"
  loop: "{{ cnpg_databases }}"
  when: cnpg_state == 'present' and (cnpg_databases | length > 0)
