---
- name: Remove Homepage
  ansible.builtin.include_tasks: remove.yml
  when: homepage_state == 'absent'

- name: Deploy Homepage namespace
  ansible.builtin.include_tasks: namespace.yml
  when: homepage_state == 'present'

- name: Deploy Homepage
  ansible.builtin.include_tasks: deploy.yml
  when: homepage_state == 'present'

- name: Verify Homepage deployment
  ansible.builtin.include_tasks: verify.yml
  when: homepage_state == 'present'
