---
- name: Remove monitoring stack
  ansible.builtin.include_tasks: remove.yml
  when: monitoring_state == 'absent'

- name: Deploy victoria-metrics-k8s-stack
  ansible.builtin.include_tasks: deploy.yml
  when: monitoring_state == 'present'

- name: Wait for Helm install job to complete
  ansible.builtin.command:
    cmd: kubectl -n kube-system wait --for=condition=complete job/helm-install-vm-k8s-stack --timeout=300s
  changed_when: false
  retries: 3
  delay: 15
  register: monitoring_helm_job
  until: monitoring_helm_job.rc == 0
  when: monitoring_state == 'present'

- name: Verify monitoring stack
  ansible.builtin.include_tasks: verify.yml
  when: monitoring_state == 'present'
