---
galaxy_info:
  role_name: nebula
  description: Deploy or remove Nebula overlay network mesh
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
