---
galaxy_info:
  role_name: traefik
  description: Deploy Traefik ingress controller configuration on K3s
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
