---
- name: Remove woodpecker
  ansible.builtin.include_tasks: remove.yml
  when: woodpecker_state == 'absent'

- name: Read woodpecker secrets from SOPS
  ansible.builtin.include_tasks: secret.yml
  when: woodpecker_state == 'present'

- name: Deploy woodpecker namespace
  ansible.builtin.include_tasks: namespace.yml
  when: woodpecker_state == 'present'

- name: Deploy woodpecker
  ansible.builtin.include_tasks: deploy.yml
  when: woodpecker_state == 'present'

- name: Wait for Helm install job to complete
  ansible.builtin.command:
    cmd: kubectl -n kube-system wait --for=condition=complete job/helm-install-woodpecker --timeout=300s
  changed_when: false
  retries: 3
  delay: 15
  register: woodpecker_helm_job
  until: woodpecker_helm_job.rc == 0
  when: woodpecker_state == 'present'

- name: Verify woodpecker
  ansible.builtin.include_tasks: verify.yml
  when: woodpecker_state == 'present'

- name: Deploy woodpecker agent
  ansible.builtin.include_tasks: agent.yml
  when: woodpecker_state == 'present'
