---
- name: Decrypt woodpecker secrets from SOPS
  ansible.builtin.command:
    cmd: sops -d {{ playbook_dir }}/../inventory/group_vars/all.sops.yml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: woodpecker_sops_raw

- name: Set woodpecker secret facts
  ansible.builtin.set_fact:
    woodpecker_db_password: "{{ (woodpecker_sops_raw.stdout | from_yaml).cnpg_woodpecker_password }}"
    woodpecker_github_client: "{{ (woodpecker_sops_raw.stdout | from_yaml).woodpecker_github_client }}"
    woodpecker_github_secret: "{{ (woodpecker_sops_raw.stdout | from_yaml).woodpecker_github_secret }}"
    woodpecker_agent_secret: "{{ (woodpecker_sops_raw.stdout | from_yaml).woodpecker_agent_secret }}"
    woodpecker_docker_registry_password: "{{ (woodpecker_sops_raw.stdout | from_yaml).docker_registry_password }}"
  no_log: true
