---
- name: Format and mount hcloud volumes
  ansible.builtin.include_tasks: mount.yml
  loop: "{{ hcloud_volumes }}"
  loop_control:
    loop_var: volume
  when:
    - hcloud_volumes_state == 'present'
    - hcloud_volumes is defined
    - hcloud_volumes | length > 0

- name: Unmount hcloud volumes
  ansible.builtin.include_tasks: remove.yml
  loop: "{{ hcloud_volumes }}"
  loop_control:
    loop_var: volume
  when:
    - hcloud_volumes_state == 'absent'
    - hcloud_volumes is defined
    - hcloud_volumes | length > 0
