---
- name: Deploy Temporal secret manifest
  ansible.builtin.template:
    src: temporal-secret.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-secret.yml
    mode: "0600"

- name: Deploy Temporal server deployment manifest
  ansible.builtin.template:
    src: temporal-server-deployment.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-server-deployment.yml
    mode: "0600"

- name: Deploy Temporal server service manifest
  ansible.builtin.template:
    src: temporal-server-service.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-server-service.yml
    mode: "0600"

- name: Deploy Temporal server NodePort service manifest
  ansible.builtin.template:
    src: temporal-server-nodeport.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-server-nodeport.yml
    mode: "0600"

- name: Deploy Temporal UI deployment manifest
  ansible.builtin.template:
    src: temporal-ui-deployment.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-ui-deployment.yml
    mode: "0600"

- name: Deploy Temporal UI service manifest
  ansible.builtin.template:
    src: temporal-ui-service.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-ui-service.yml
    mode: "0600"

- name: Deploy Temporal UI ingress manifest
  ansible.builtin.template:
    src: temporal-ui-ingress.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/temporal-ui-ingress.yml
    mode: "0600"
