---
- name: Wait for Temporal server deployment
  ansible.builtin.command:
    cmd: kubectl -n {{ temporal_namespace }} rollout status deployment/temporal-server --timeout=300s
  changed_when: false
  retries: 3
  delay: 15
  register: temporal_server_rollout
  until: temporal_server_rollout.rc == 0

- name: Wait for Temporal UI deployment
  ansible.builtin.command:
    cmd: kubectl -n {{ temporal_namespace }} rollout status deployment/temporal-ui --timeout=300s
  changed_when: false
  retries: 3
  delay: 15
  register: temporal_ui_rollout
  until: temporal_ui_rollout.rc == 0
