---
- name: Decrypt forward proxy secrets from SOPS
  ansible.builtin.command:
    cmd: sops -d {{ playbook_dir }}/../inventory/group_vars/all.sops.yml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: forward_proxy_sops_raw

- name: Set forward proxy secret facts
  ansible.builtin.set_fact:
    forward_proxy_users: "{{ (forward_proxy_sops_raw.stdout | from_yaml).forward_proxy_users }}"
  no_log: true
