---
- name: Read hcloud token from SOPS
  ansible.builtin.command:
    cmd: sops -d --extract '["hcloud_token"]' {{ playbook_dir }}/../../secrets/api-tokens.sops.yaml
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true
  register: hcloud_csi_token_result

- name: Set hcloud token fact
  ansible.builtin.set_fact:
    hcloud_csi_token: "{{ hcloud_csi_token_result.stdout }}"
  no_log: true

- name: Deploy hcloud secret manifest
  ansible.builtin.template:
    src: hcloud-csi-secret.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/hcloud-csi-secret.yml
    mode: "0600"
