---
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: Run update_cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ ubuntu24_updates_cache_valid_time }}"
  tags:
    - always

- name: Install packages
  ansible.builtin.apt:
    pkg: "{{ ubuntu24_required_packages }}"
  tags:
    - always
