---
- name: Deploy docker-registry htpasswd secret manifest
  ansible.builtin.template:
    src: docker-registry-secret.yml.j2
    dest: /var/lib/rancher/k3s/server/manifests/docker-registry-secret.yml
    mode: "0600"
